name: virtualband

services:

  backend:
    build: ./Backend
    restart: unless-stopped
    volumes:
      - ./Backend:/VirtualBand/Backend
    ports:
      - "5000:5000"
    depends_on:
      - database

    
  frontend:
    build: ./Frontend/bandmate-builder            # context is Frontend/
    ports:
      - "3001:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
  
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leahzhang1595995_db_user
      - MONGO_INITDB_ROOT_PASSWORD=85a881b080ee41c2887ab5547620844c
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: {}
    
  