name: virtualband

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./Backend:/app
      - ~/.aws:/root/.aws:ro          # <- add this so boto3 can auth via your local AWS profile
    command: /usr/local/bin/docker-entrypoint.sh   # <- run our entrypoint
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file: 
      - .env

    
  frontend:
    build: ./Frontend/bandmate-builder            # context is Frontend/
    ports:
      - "3001:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
  
  database:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leahzhang1595995_db_user
      - MONGO_INITDB_ROOT_PASSWORD=85a881b080ee41c2887ab5547620844c
    volumes:
      - mongo_data:/data/db
      - "./Backend/band/db/init:/docker-entrypoint-initdb.d:ro"

    
volumes:
  mongo_data: {}
    
